prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
      - job_name: 'homelab-monitor'
        static_configs:
          - targets: ['homelab:5000']
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['homelab:9100']


prometheus:
  service:
    type: NodePort
    nodePort: 30090



grafana:
  service:
    type: NodePort
    nodePort: 30300
  persistence:
    enabled: true
    size: 1Gi
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL
